### ISSUE TITLE
Error uuid in tasksTask.model.php

### ISSUE THREAD

**Issue by AlexBelfegor** [1312inc/Tasks-app-Webasyst#15]
[https://github.com/1312inc/Tasks-app-Webasyst/blob/main/lib/models/tasksTask.model.php](url)
>    public function getWithoutUuid($limit = 100)
    {
        return $this->select('*')
            ->where('uuid is null')
            ->limit($limit

`Query Error 1054: Unknown column 'uuid' in 'where clause'
Query: SELECT * FROM tasks_task WHERE (uuid is null) ORDER BY id desc LIMIT 100`

**Comment by kerstvo** [comment]
Скорее всего это ошибка залогировалась в процессе метаобновления. Или повторяется?
