### ISSUE TITLE
Не завелось на centos php 7.4

### ISSUE THREAD

**Issue by Zizix** [1312inc/Tasks-app-Webasyst#27]
Так же у вас на сайте не смог посмтореть демо, белый экран, а приложение очень интересное!

Fatal error: Uncaught TypeError: Return value of tasksTaskLogModel::findFirstLogForContactId() must be of the type array, null returned in /home/test/sites/test.org/wa-apps/tasks/lib/models/tasksTaskLog.model.php:628 Stack trace: #0 /home/test/sites/test.org/wa-apps/tasks/lib/classes/Services/tasksTinyAddService.class.php(77): tasksTaskLogModel->findFirstLogForContactId(1) #1 /home/test/sites/test.org/wa-apps/tasks/lib/classes/Services/tasksTinyAddService.class.php(18): tasksTinyAddService->canShow(Object(waAuthUser)) #2 /home/test/sites/test.org/wa-apps/tasks/lib/actions/backend/tasksBackend.action.php(41): tasksTinyAddService->getAd(Object(waAuthUser)) #3 /home/test/sites/test.org/wa-system/controller/waViewAction.class.php(188): tasksBackendAction->execute() #4 /home/test/sites/test.org/wa-system/controller/waViewController.class.php(86): waViewAction->display() #5 /home/test/sites/test.org/wa-system/controller/waDefaultViewController.class.php(48): waViewController->executeAct in /home/test/sites/test.org/wa-apps/tasks/lib/models/tasksTaskLog.model.php on line 628

**Comment by vofka** [comment]
Спасибо за сообщение! Исправлено в `main`.
Попробуйте, пожалуйста, свежий релиз — https://github.com/1312inc/Tasks-app-Webasyst/releases/tag/v2.6.2
